### ISSUE TITLE
请教大佬，添加域名后默认的阈值怎么修改？

### ISSUE THREAD

**Issue by doublog** [aoaostar/v8cdn#1]
现在添加域名以后，默认的域名阈值是大佬的域名，请问这个可以修改么？使用了大佬的程序，稍微做了一点点修改，但是有明确指出是大佬提供的源代码。感谢大佬提供！

**Comment by aoaostar** [comment]
你说的是后端api地址吗？前端根目录`config.js`文件里修改就行了

**Comment by doublog** [comment]
不是的，是登录账户以后，添加域名，域名出现的那个默认的cname是指向的大佬的域名。

**Comment by doublog** [comment]
还有一个问题就是，我可以在你这个系统里面管理直接使用cf dns的域名，但是生效不生效，我没测试。我看到的是使用了cf自己的ns的域名，在你这个系统里也可以管理和删除。

**Comment by aoaostar** [comment]
> 还有一个问题就是，我可以在你这个系统里面管理直接使用cf dns的域名，但是生效不生效，我没测试。我看到的是使用了cf自己的ns的域名，在你这个系统里也可以管理和删除。

这个本来就是可以的，在别人的partner添加的域名同样是可以管理的

**Comment by doublog** [comment]
> > 还有一个问题就是，我可以在你这个系统里面管理直接使用cf dns的域名，但是生效不生效，我没测试。我看到的是使用了cf自己的ns的域名，在你这个系统里也可以管理和删除。
> 
> 这个本来就是可以的，在别人的partner添加的域名同样是可以管理的

因为我是之前用过Ze3kr大佬写的那个cfp管理面板，我看他那个面板里是只能管理cfp添加的域名，直接用cf dns的域名是无法在cfp面板进行管理的。所以觉得奇怪，咨询一下。呵呵
![image](https://user-images.githubusercontent.com/34877606/133873301-2fbe88c4-202d-47b8-bb78-6461d6d726f9.png)

另外我说的那个问题是这样，我截图给大佬看下。
![image](https://user-images.githubusercontent.com/34877606/133873278-3383943f-047e-43ce-8c79-9f6fbd57f735.png)

**Comment by aoaostar** [comment]
> > > 还有一个问题就是，我可以在你这个系统里面管理直接使用cf dns的域名，但是生效不生效，我没测试。我看到的是使用了cf自己的ns的域名，在你这个系统里也可以管理和删除。
> > 
> > 
> > 这个本来就是可以的，在别人的partner添加的域名同样是可以管理的
> 
> 因为我是之前用过Ze3kr大佬写的那个cfp管理面板，我看他那个面板里是只能管理cfp添加的域名，直接用cf dns的域名是无法在cfp面板进行管理的。所以觉得奇怪，咨询一下。呵呵
> ![image](https://user-images.githubusercontent.com/34877606/133873301-2fbe88c4-202d-47b8-bb78-6461d6d726f9.png)
> 
> 另外我说的那个问题是这样，我截图给大佬看下。
> ![image](https://user-images.githubusercontent.com/34877606/133873278-3383943f-047e-43ce-8c79-9f6fbd57f735.png)

这个得修改后端源代码，重新编译

**Comment by doublog** [comment]
> > > > 还有一个问题就是，我可以在你这个系统里面管理直接使用cf dns的域名，但是生效不生效，我没测试。我看到的是使用了cf自己的ns的域名，在你这个系统里也可以管理和删除。
> > > 
> > > 
> > > 这个本来就是可以的，在别人的partner添加的域名同样是可以管理的
> > 
> > 
> > 因为我是之前用过Ze3kr大佬写的那个cfp管理面板，我看他那个面板里是只能管理cfp添加的域名，直接用cf dns的域名是无法在cfp面板进行管理的。所以觉得奇怪，咨询一下。呵呵
> > ![image](https://user-images.githubusercontent.com/34877606/133873301-2fbe88c4-202d-47b8-bb78-6461d6d726f9.png)
> > 另外我说的那个问题是这样，我截图给大佬看下。
> > ![image](https://user-images.githubusercontent.com/34877606/133873278-3383943f-047e-43ce-8c79-9f6fbd57f735.png)
> 
> 这个得修改后端源代码，重新编译

呃，那我就不会了，哈哈，纯小白一个。。感谢大佬耐心解答！

**Comment by aoaostar** [comment]
> > > > > 还有一个问题就是，我可以在你这个系统里面管理直接使用cf dns的域名，但是生效不生效，我没测试。我看到的是使用了cf自己的ns的域名，在你这个系统里也可以管理和删除。
> > > > 
> > > > 
> > > > 这个本来就是可以的，在别人的partner添加的域名同样是可以管理的
> > > 
> > > 
> > > 因为我是之前用过Ze3kr大佬写的那个cfp管理面板，我看他那个面板里是只能管理cfp添加的域名，直接用cf dns的域名是无法在cfp面板进行管理的。所以觉得奇怪，咨询一下。呵呵
> > > ![image](https://user-images.githubusercontent.com/34877606/133873301-2fbe88c4-202d-47b8-bb78-6461d6d726f9.png)
> > > 另外我说的那个问题是这样，我截图给大佬看下。
> > > ![image](https://user-images.githubusercontent.com/34877606/133873278-3383943f-047e-43ce-8c79-9f6fbd57f735.png)
> > 
> > 
> > 这个得修改后端源代码，重新编译
> 
> 呃，那我就不会了，哈哈，纯小白一个。。感谢大佬耐心解答！

添加域名的时候，必须添加www和@的解析值，之后我再弄成配置吧

**Comment by doublog** [comment]
> > > > > > 还有一个问题就是，我可以在你这个系统里面管理直接使用cf dns的域名，但是生效不生效，我没测试。我看到的是使用了cf自己的ns的域名，在你这个系统里也可以管理和删除。
> > > > > 
> > > > > 
> > > > > 这个本来就是可以的，在别人的partner添加的域名同样是可以管理的
> > > > 
> > > > 
> > > > 因为我是之前用过Ze3kr大佬写的那个cfp管理面板，我看他那个面板里是只能管理cfp添加的域名，直接用cf dns的域名是无法在cfp面板进行管理的。所以觉得奇怪，咨询一下。呵呵
> > > > ![image](https://user-images.githubusercontent.com/34877606/133873301-2fbe88c4-202d-47b8-bb78-6461d6d726f9.png)
> > > > 另外我说的那个问题是这样，我截图给大佬看下。
> > > > ![image](https://user-images.githubusercontent.com/34877606/133873278-3383943f-047e-43ce-8c79-9f6fbd57f735.png)
> > > 
> > > 
> > > 这个得修改后端源代码，重新编译
> > 
> > 
> > 呃，那我就不会了，哈哈，纯小白一个。。感谢大佬耐心解答！
> 
> 添加域名的时候，必须添加www和@的解析值，之后我再弄成配置吧

其实我个人觉得，非cfp添加的域名的那个管理NS解析记录和可删除的效果可以不添加上去。。这样感觉像个全局管理。。

**Comment by doublog** [comment]
个人感觉，有点像是获取了cf账号的管理权限那种了。。可能只是我的错觉吧。从一个使用者角度来看的话。我个人是这样认为的。

**Comment by aoaostar** [comment]
> 个人感觉，有点像是获取了cf账号的管理权限那种了。。可能只是我的错觉吧。从一个使用者角度来看的话。我个人是这样认为的。

cloudflare没有提供区分的方法，只有全局的api，其实cloudflare partner就添加cname接入这个作用，其他管理api都是通用的

**Comment by doublog** [comment]
> > 个人感觉，有点像是获取了cf账号的管理权限那种了。。可能只是我的错觉吧。从一个使用者角度来看的话。我个人是这样认为的。
> 
> cloudflare没有提供区分的方法，只有全局的api，其实cloudflare partner就添加cname接入这个作用，其他管理api都是通用的

好吧，谢谢大佬解惑！
