### ISSUE TITLE
程序很好用，可以增加在线更新缓存的功能吗？

### ISSUE THREAD

**Issue by ludashi2020** [aoaostar/v8cdn#3]
如果可以的话，那就太棒了。

**Comment by aoaostar** [comment]
可以，有空+

**Comment by sucangit** [comment]
＋1，之前用的python版本，今天迁移服务器换成了新版本，简洁实用，感谢作者。另外问一下，本地重新生成前端部署后(局部微调)，登陆提示email为必填字段，不知道哪儿出问题了，看日志也正常的...

**Comment by aoaostar** [comment]
@sucangit 登录界面f12看看email是否传过去了，原来用的username字段，后面我改成了email，可能是你的cdn缓存导致页面未更新，我搭建的是没有问题的

**Comment by sucangit** [comment]
@aoaostar  感谢！已经解决。是本地资源问题 ( 部署前明明拉取了最新的，奇怪。)
