### ISSUE TITLE
能否在无hostkey的情况下使用邮箱和globalkey登录管理DNS

### ISSUE THREAD

**Issue by HanadaLee** [aoaostar/v8cdn#4]
没有parter权限，但是只是想自己搭个面板管理自己账号下的cfp接入域名，ZE3kr那边如果key失效可以用账号和global key登录这边能否也能在无hostkey情况下管理dns

**Comment by aoaostar** [comment]
> 没有parter权限，但是只是想自己搭个面板管理自己账号下的cfp接入域名，ZE3kr那边如果key失效可以用账号和global key登录这边能否也能在无hostkey情况下管理dns

可以是可以，但是我没写，partner只是帮你生成了一个key而已

**Comment by HanadaLee** [comment]
我其实就是想搞个能管理的面板，cfp接入的域名没法在官网上管理，自己调用api又麻烦，用其他人托管的dns面板又经常这家坏那家出问题（ze3kr那个面板ui太不喜欢了）

**Comment by hhhkkk520** [comment]
赞同，希望作者可以考虑开发此项功能，就是说在没有Host API的情况下可以作为一个用API管理CFP DNS的工具，可以参考ze3kr面板如果Host API留空，就会自动切换为Global API登陆的模式
这样如果用别家的CFP被封或跑路后，自己也有工具可以管理DNS
